spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tech_shop?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      #连接池名称
      pool-name: hikariPool
      #最小空闲连接数
      minimum-idle: 5
      #最大连接数
      maximum-pool-size: 20
      #连接空闲超时时间（毫秒）
      idle-timeout: 30000
      #连接最大存活时间（毫秒）
      max-lifetime: 1800000
      #链接超时时间（毫秒）
      connection-timeout: 30000
      #测试连接是否有效的查询语句
      connection-test-query: SELECT 1
mybatis:
  # mapper文件位置
  mapper-locations: classpath:mapper/*.xml
  # 实体类包路径
  type-aliases-package: com.jhtx.tl.infra.repository.entity
  configuration:
    # 开启驼峰命名转换
    map-underscore-to-camel-case: true
    # 日志实现
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl